# Generated by Django 4.2.6 on 2023-10-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='contacts',
            field=models.ManyToManyField(related_name='contact_events', to='contacts.contact'),
        ),
    ]
